### ISSUE TITLE
Drop the gokrb5 replace directive

### ISSUE THREAD

**Issue by codebien** [grafana/xk6-kerberos#35]
The `gokrb5` project is not very active. We already applied a major patch in [a fork under Grafana org](https://github.com/grafana/gokrb5). As there isn't any evolution on the upstream repository, we intend to do a next step on the fork and make the "github.com/grafana/gokrb5" available as a go importable library.

It allows to drop [the replacement](https://github.com/grafana/xk6-kerberos/blob/4d945d9794ad810aa5c6c4ac7234e52f55163dd8/go.mod#L58) in the `go.mod` file and consequentially fix the CI's step for the linter and simplify the installation/building procedures.

**Comment by joanlopez** [comment]
### Action plan (27/05)
*(to be confirmed)*

- [ ] Merge `testenv` pull request: https://github.com/grafana/gokrb5-test/pull/1
- **Q1:** Update Docker images & references? (from `jcmturner/gokrb5` to `grafana/gokrb5`) - *I guess so*
  - [ ] Open & merge a pull request to replace references in `gokrb5-test`
  - **Q1.1:** Use ghcr.io instead? - *A bit less "official, probably easier"*
  - **Q1.2:** Add a release workflow (automate it)? - *Worths the effort, probably easier"* 
  - [ ] Open & merge a pull request to automate the publication of `gokrb5`-related images to ghcr.io
- [ ] Open & merge a pull request to replace references in `gokrb5`
- [ ] Merge https://github.com/grafana/gokrb5/pull/1
- [ ] Open & merge a pull request to replace paths and `go.mod` (_v8_) in `gokrb5` (to make it "importable")
- [ ] Open & merge a pull request in `xk6-kerberos` to:
  - [ ] Drop the `replace` directive
  - [ ] Update the dependency (`go.mod`) and imports.
- **Q2:** Do we want to manage versioning? - *I guess not, as it's not required*
- **Q3:** Anything else? 
- **Q3.1:** Add a _WARNING_ in both `gokrb5` repositories?
